arguments:
  image: "/gpfs/fs5/nrcan/nrcan_geobase/work/transfer/work/deep_learning/dominica/data/Dominica_West_17OCT11_WV02_BGRN_COG.tif"
  model: ./deep_learning_model/4cls_RGB_5_1_2_3_scripted.pt   # Name of Extraction Model: str
  bbox: None                      # "minx, miny, maxx, maxy" 
  work_dir: ./dask_geo_deep_learning/dask_geo_inference   # Working Directory: str
  bands_requested: '3,2,1'                    # requested Bands
  vec: False                      # Vector Coversion: bool 
  vec: False                      # Vector Conversion: bool 
  yolo: False                     # YOLO Conversion: bool
  coco: False                     # COCO Conversion: bool
  device: "gpu"                   # cpu or gpu: str
  gpu_id: 0
  mgpu: False
  classes : 5
  patch_size: 1024
