arguments:
  bbox: None                      # "minx, miny, maxx, maxy" 
  model: "/gpfs/fs5/nrcan/nrcan_geobase/work/dev/datacube/parallel/deep_learning_model/4cls_RGB_5_1_2_3_scripted.pt"   # Name of Extraction Model: str
  work_dir: "/gpfs/fs5/nrcan/nrcan_geobase/work/dev/datacube/parallel/geo_deep_learning_results"                 # Working Directory: str
  data_dir: "/gpfs/fs5/nrcan/nrcan_geobase/work/dev/datacube/parallel/deep_learning/geo-deep-learning/tests/data/inference/test.csv"
  bands_requested: 'red,green,blue'                  # Batch size
  vec: False                      # Vector Coversion: bool 
  vec: False                      # Vector Conversion: bool 
  yolo: False                     # YOLO Conversion: bool
  coco: False                     # COCO Conversion: bool
  device: "gpu"                   # cpu or gpu: str
  gpu_id: 0
  chunk_size: 1024
  n_workers: 16
  memory_limit: "100GB"
  enhance_clip_limit: 25
  mgpu : False
  classes : 5
